#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 mark0402

# -*- coding: utf-8 -*-
"""
把任意图片转换为 HC32 TFT 可直接显示的 RGB565 头文件。

生成的数组可直接喂给 LCD_Show_Image(x, y, w, h, data):
  - 每像素 2 字节, RGB565, 高字节在前 (MSB first), 与 LCD_Address_Set + SPI 直推匹配
  - 行优先: 从左到右, 从上到下
  - 透明像素 (alpha < 阈值) 用 --bg 指定的背景色填充 (默认黑色 0x0000)

用法 (在 project/tools 目录下):
  python gen_image.py TitansLogo.png
      默认输出 ../source/guislice/titans_logo.h, 宏名 TITANS_LOGO

  python gen_image.py icon.png -n ICON -o ../source/guislice/icon.h
      自定义宏名与输出路径

  python gen_image.py photo.jpg --resize 120x60
      先缩放到 120x60 再转换 (屏幕只有 240x135, 大图必须缩)

  python gen_image.py logo.png --bg FFFF
      透明区域填白 (默认填黑 0000)

产物头文件形如:
  #define TITANS_LOGO_W 201
  #define TITANS_LOGO_H 47
  static const uint8_t g_au8TitansLogo[18894] = { ... };

需要: pip install pillow
"""

import argparse
import os
import re

from PIL import Image


def rgb888_to_rgb565(r, g, b):
    """RGB888 -> RGB565 (5-6-5)"""
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def parse_resize(s):
    m = re.match(r"^\s*(\d+)\s*[xX]\s*(\d+)\s*$", s)
    if not m:
        raise SystemExit("--resize 格式应为 WxH, 例如 201x47")
    return int(m.group(1)), int(m.group(2))


def default_name(out_path, src_path):
    """由输出/输入文件名推导宏名: titans_logo.h -> TITANS_LOGO"""
    base = os.path.splitext(os.path.basename(out_path or src_path))[0]
    base = re.sub(r"[^0-9A-Za-z]+", "_", base).strip("_").upper()
    if base and base[0].isdigit():
        base = "IMG_" + base
    return base or "IMAGE"


def build_header(name, w, h, data, per_line, src_name):
    guard = "_%s_DATA_H" % name
    lines = [
        "// Auto-generated by gen_image.py from %s (RGBA -> RGB565, MSB first)." % src_name,
        "// Transparent pixels (alpha < threshold) are replaced by the --bg color.",
        "#ifndef %s" % guard,
        "#define %s" % guard,
        "#include <stdint.h>",
        "#define %s_W %d" % (name, w),
        "#define %s_H %d" % (name, h),
        "static const uint8_t g_au8%s[%d] = {" % (
            "".join(p.capitalize() for p in name.split("_")), w * h * 2),
    ]
    for i in range(0, len(data), per_line):
        chunk = data[i:i + per_line]
        lines.append("  " + ",".join("0x%02X" % b for b in chunk) + ",")
    # 去掉最后一个逗号, 收尾
    if lines[-1].endswith(","):
        lines[-1] = lines[-1][:-1]
    lines.append("};")
    lines.append("#endif")
    return "\n".join(lines) + "\n"


def main():
    here = os.path.dirname(os.path.abspath(__file__))

    ap = argparse.ArgumentParser(description="image -> RGB565 C header for HC32 TFT")
    ap.add_argument("src", help="source image (png/jpg/bmp)")
    ap.add_argument("-o", "--output", default=None,
                    help="output .h path (default: ../source/guislice/<src stem>.h)")
    ap.add_argument("-n", "--name", default=None,
                    help="macro name prefix (default: derived from file name)")
    ap.add_argument("--resize", default=None, help="resize to WxH before converting")
    ap.add_argument("--bg", default="0000",
                    help="fill color for transparent pixels, RGB565 hex (default 0000=black)")
    ap.add_argument("--alpha-threshold", type=int, default=128,
                    help="alpha below this is treated as transparent (default 128)")
    ap.add_argument("--per-line", type=int, default=24, help="bytes per line in output")
    args = ap.parse_args()

    if not os.path.exists(args.src):
        raise SystemExit("找不到图片: %s" % args.src)

    out_path = args.output
    if out_path is None:
        stem = os.path.splitext(os.path.basename(args.src))[0]
        out_path = os.path.join(here, "..", "source", "guislice", stem + ".h")
    out_path = os.path.abspath(out_path)

    name = args.name or default_name(out_path, args.src)

    try:
        bg = int(args.bg, 16) & 0xFFFF
    except ValueError:
        raise SystemExit("--bg 应为 RGB565 十六进制, 例如 0000 / FFFF / F800")

    img = Image.open(args.src)
    if args.resize:
        img = img.resize(parse_resize(args.resize), Image.LANCZOS)

    # 统一到 RGBA: 无 alpha 通道的图全部视为不透明
    img = img.convert("RGBA")
    w, h = img.size
    px = img.load()

    data = bytearray()
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            if a < args.alpha_threshold:
                v = bg
            else:
                v = rgb888_to_rgb565(r, g, b)
            data.append((v >> 8) & 0xFF)   # MSB first
            data.append(v & 0xFF)

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(build_header(name, w, h, data, args.per_line,
                             os.path.basename(args.src)))

    print("生成 %s (%dx%d, %d 字节 = %d 像素 x 2) -> %s"
          % (name, w, h, len(data), w * h, out_path))
    if w > 240 or h > 135:
        print("警告: 图片 %dx%d 超过屏幕 240x135, LCD_Show_Image 会直接 return, 请用 --resize 缩小"
              % (w, h))


if __name__ == "__main__":
    main()
