#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 mark0402

# -*- coding: utf-8 -*-
"""
生成 HC32F460 中文 16x16 点阵字库 (纯十六进制, 源文件不含任何中文字符; 与编译器版本无关)

输出 (写入 ../source):
  chinese_font.h      类型定义 + 函数声明
  chinese_font_data.c 单字点阵数组 (按 Unicode 码点索引)
  cn_strings.h        常用中文句子的 UTF-8 字节数组 (便于直接调用)

用法:
  python gen_chinese_font.py
需要: pip install pillow   (本项目环境已装 PIL 11.3)

增删汉字: 改下面的 WORDS / STRINGS 即可, 重跑脚本。
"""
import os

from PIL import Image, ImageDraw, ImageFont

# ---- 中文字体 (黑体笔画均匀, 16x16 最清晰) ----
FONT_PATHS = [
    r"C:\Windows\Fonts\simhei.ttf",
    r"C:\Windows\Fonts\simsun.ttc",
    r"C:\Windows\Fonts\msyh.ttc",
    r"C:\Windows\Fonts\simkai.ttf",
]

W, H = 16, 16  # 点阵尺寸

# ---- 单字字库: 去重后的所有汉字 (脚本会从 STRINGS 自动补全, 这里可加额外单字) ----
EXTRA_CHARS = list("年月日时分秒总压流率开关上下左右")

# ---- 常用中文句子: 宏名(ASCII) -> 中文 ----
# 改这里即可增删要在 UI 显示的整句中文
STRINGS = {
    "EMS_TITLE":  "能源管理系统",
    "SET":        "设置",
    "TIME":       "时间",
    "DATE":       "日期",
    "SAVE":       "保存",
    "CANCEL":     "取消",
    "BACK":       "返回",
    "MENU":       "菜单",
    "HOME":       "首页",
    "VOLTAGE":    "电压",
    "CURRENT":    "电流",
    "POWER":      "功率",
    "TEMP":       "温度",
    "ENERGY":     "能量",
    "STATUS":     "状态",
    "RUN":        "运行",
    "STOP":       "停止",
    "FAULT":      "故障",
    "WARN":       "警告",
    "NORMAL":     "正常",
    "PARAM":      "参数",
    "SYSTEM":     "系统",
    "VERSION":    "版本",
    "ABOUT":      "关于",
    "LANG":       "语言",
    "BRIGHT":     "亮度",
    "CLEAR":      "清除",
    "CONFIRM":    "确认",
    "CHARGE":     "充电",
    "DISCHARGE":  "放电",
    "LOAD":       "负载",
    "GRID":       "电网",
    "PV":         "光伏",
    "BATTERY":    "电池",
    "INVERTER":   "逆变",
    "FREQ":       "频率",
    "CAPACITY":   "容量",
    "MODE":       "模式",
    "AUTO":       "自动",
    "MANUAL":     "手动",
    "ON":         "开",
    "OFF":        "关",
    "RUNNING":    "运行中",
    "SHUTDOWN":   "已关机",
    "CHINESE_DEMO": "中文显示正常",
    "RECT":       "矩形",
    "TRI":        "三角形",
    "PENTA":      "五角星",
    "HEXAGRAM":   "六芒星",
    "TIME_SET":   "时间设置",
    "YEAR":       "年",
    "MONTH":      "月",
    "DAY":        "日",
    "HOUR":       "时",
    "MIN":        "分",
    "SEC":        "秒",
}


def find_font():
    for p in FONT_PATHS:
        if os.path.exists(p):
            return p
    raise SystemExit("未找到中文字体, 请修改 FONT_PATHS 指向本机中文字体(.ttf/.ttc)")


def render_glyph(ch, font):
    """渲染单个汉字为 16x16 单色点阵, 返回 16 个 16-bit 行值(高位在左)。"""
    img = Image.new("L", (W, H), 0)
    d = ImageDraw.Draw(img)
    d.text((0, 0), ch, fill=255, font=font)
    # 裁剪到字形包围盒并居中, 避免黑体在 16px 下被顶部裁切
    bbox = img.getbbox()
    if bbox:
        crop = img.crop(bbox)
        cw, chh = crop.size
        ox = (W - cw) // 2
        oy = (H - chh) // 2
        img = Image.new("L", (W, H), 0)
        img.paste(crop, (ox, oy))
    px = img.load()
    rows = []
    for y in range(H):
        row = 0
        for x in range(W):
            row = (row << 1) | (1 if px[x, y] > 128 else 0)
        rows.append(row)
    return rows


def utf8_bytes(s):
    return [b for b in s.encode("utf-8")]


def main():
    fp = find_font()
    font = ImageFont.truetype(fp, W)

    # 收集所有单字 (去重, 保持顺序)
    seen = set()
    chars = []
    for s in STRINGS.values():
        for c in s:
            if c not in seen:
                seen.add(c)
                chars.append(c)
    for c in EXTRA_CHARS:
        if c not in seen:
            seen.add(c)
            chars.append(c)

    glyphs = []  # (unicode, [16 行值])
    for c in chars:
        glyphs.append((ord(c), render_glyph(c, font)))

    out_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "source"))
    os.makedirs(out_dir, exist_ok=True)

    # ---------- chinese_font.h ----------
    h = [
        "// Auto-generated by gen_chinese_font.py -- DO NOT EDIT",
        "#ifndef __CHINESE_FONT_H",
        "#define __CHINESE_FONT_H",
        "#include <stdint.h>",
        "",
        "#define CN_FONT_W 16",
        "#define CN_FONT_H 16",
        "",
        "typedef struct {",
        "    uint16_t unicode;",
        "    const uint8_t data[32];   // 16x16, row-major, MSB left",
        "} cn_glyph_t;",
        "",
        "extern const cn_glyph_t g_cn_font[];",
        "extern const uint16_t    g_cn_font_num;",
        "",
        "// look up a glyph by unicode; returns data ptr or NULL",
        "const uint8_t* CN_FindGlyph(uint16_t unicode);",
        "// draw one 16x16 glyph, (x,y)=top-left corner",
        "void LCD_ShowChinese(uint16_t x, uint16_t y, uint16_t color, const uint8_t* g);",
        "// draw a UTF-8 byte string (CJK + ASCII mixed); returns pixel width drawn",
        "uint16_t LCD_ShowChineseStr(uint16_t x, uint16_t y, uint16_t color, const uint8_t* utf8);",
        "",
        "#endif",
    ]
    with open(os.path.join(out_dir, "chinese_font.h"), "w", encoding="utf-8") as f:
        f.write("\n".join(h) + "\n")

    # ---------- chinese_font_data.c ----------
    c = [
        "// Auto-generated by gen_chinese_font.py -- DO NOT EDIT",
        '#include "chinese_font.h"',
        "",
        "const cn_glyph_t g_cn_font[] = {",
    ]
    for u, rows in glyphs:
        bytes_arr = []
        for v in rows:
            bytes_arr.append((v >> 8) & 0xFF)
            bytes_arr.append(v & 0xFF)
        hexstr = ", ".join("0x%02X" % b for b in bytes_arr)
        c.append("  {0x%04X, {%s}}, // U+%04X" % (u, hexstr, u))
    c.append("};")
    c.append("const uint16_t g_cn_font_num = (uint16_t)(sizeof(g_cn_font) / sizeof(g_cn_font[0]));")
    with open(os.path.join(out_dir, "chinese_font_data.c"), "w", encoding="utf-8") as f:
        f.write("\n".join(c) + "\n")

    # ---------- cn_strings.h ----------
    s = [
        "// Auto-generated by gen_chinese_font.py -- DO NOT EDIT",
        "#ifndef __CN_STRINGS_H",
        "#define __CN_STRINGS_H",
        "#include <stdint.h>",
        "",
        "// UTF-8 byte arrays for common Chinese strings (no CJK literals in source)",
        "// pass to LCD_ShowChineseStr(), e.g. LCD_ShowChineseStr(x, y, GREEN, CNSTR_SET);",
    ]
    for name, txt in STRINGS.items():
        b = utf8_bytes(txt)
        hexstr = ", ".join("0x%02X" % x for x in b) + ", 0x00"
        s.append("static const uint8_t CNSTR_%s[] = {%s};" % (name, hexstr))
    s.append("")
    s.append("#endif")
    with open(os.path.join(out_dir, "cn_strings.h"), "w", encoding="utf-8") as f:
        f.write("\n".join(s) + "\n")

    print("生成 %d 个汉字, %d 个字符串 -> %s" % (len(glyphs), len(STRINGS), out_dir))


if __name__ == "__main__":
    main()
