/* SPDX-License-Identifier: MIT */
/* Copyright (c) 2026 mark0402 */
// Auto-generated by gen_chinese_font.py -- DO NOT EDIT
#ifndef __CHINESE_FONT_H
#define __CHINESE_FONT_H
#include <stdint.h>

#define CN_FONT_W 16
#define CN_FONT_H 16

typedef struct {
    uint16_t unicode;
    const uint8_t data[32];   // 16x16, row-major, MSB left
} cn_glyph_t;

extern const cn_glyph_t g_cn_font[];
extern const uint16_t    g_cn_font_num;

// look up a glyph by unicode; returns data ptr or NULL
const uint8_t* CN_FindGlyph(uint16_t unicode);
// draw one 16x16 glyph, (x,y)=top-left corner
void LCD_ShowChinese(uint16_t x, uint16_t y, uint16_t color, const uint8_t* g);
// draw a UTF-8 byte string (CJK + ASCII mixed); returns pixel width drawn
uint16_t LCD_ShowChineseStr(uint16_t x, uint16_t y, uint16_t color, const uint8_t* utf8);

#endif
